export const bankImages:Record<string, string> = {
  '078': '/banks/khavar mianeh.svg',
  '056': '/banks/saman.svg',
  '016': '/banks/keshavarzi.svg',
  '017': '/banks/melli.svg',
  '061': '/banks/shahr.svg',
  '012': '/banks/mellat.svg',
  '066': '/banks/day.svg',
  '019': '/banks/saderat.svg',
  '013': '/banks/refah.svg',
  '018': '/banks/tejarat.svg',
  '015': '/banks/sepah.svg',
  '064': '/banks/gardeshgary.svg',
  '057': '/banks/pasargad.svg',
  '062': '/banks/ayande.svg',
  '055': '/banks/eghtesad novin.svg',
  '054': '/banks/parsian.svg',
  '014': '/banks/maskan.svg',
  '069': '/banks/iran zamin.svg',
  '010': '/banks/sarmayeh.svg',
  // '058': '/banks/sarmayeh.svg',
  '070': '/banks/resalat.svg',
  '059': '/banks/sina.svg',
  '022': '/banks/tosee taavon.svg',
  '053': '/banks/karafarin.svg',
  '021': '/banks/post.svg',
  '011': '/banks/sanat madan.svg',
  '060': '/banks/mehr iran.svg',
  '020': '/banks/tosee saderat.svg',
  '075': '/banks/melal.svg',
}
